
document.addEventListener('DOMContentLoaded', () => {
//toggle
const toggle = document.getElementById('theme-toggle');
const label = document.getElementById('theme-label');

function toggleMode() {
    if (!toggle.checked) {
        document.body.classList.remove('light-mode');
        label.textContent = 'Dark Mode';
    } else {
        document.body.classList.add('light-mode');
        label.textContent = 'Light Mode';
    }
}

// call it once on load
toggleMode();

// add event listener for further changes
toggle.addEventListener('change', toggleMode);


//Search
const searchInput = document.getElementById('search-input');
const suggestionsList = document.getElementById('suggestions-list');
let finalQuery = '';
const items = [
    '123',
    'accessibility',
    'activity',
    'add',
    'airplane',
    'alarm',
    'alert',
    'alien pixel',
    'alien',
    'ambulance',
    'anchor',
    'apple',
    'apron',
    'aquarius',
    'arch bridge',
    'archery',
    'archive',
    'aries',
    'arrivals',
    'arrow circle down',
    'arrow down basic',
    'arrow down line',
    'arrow down',
    'arrow left basic',
    'arrow left line',
    'arrow left',
    'arrow northeast',
    'arrow northwest',
    'arrow right basic',
    'arrow right line',
    'arrow right',
    'arrow southeast',
    'arrow southwest',
    'arrow turn left',
    'arrow turn right',
    'arrow up basic',
    'arrow up line',
    'arrow up',
    'arrows horizontal',
    'arrows swap horizontally',
    'arrows swap vertically',
    'arrows vertical',
    'art',
    'asterisk',
    'atm',
    'attachment',
    'avocado',
    'baby bottle',
    'baby',
    'backpack',
    'backward',
    'badge',
    'bag',
    'baggage claim',
    'balloon',
    'banana',
    'barcode',
    'barricade',
    'baseball cap',
    'baseball',
    'basketball',
    'bathtub shower',
    'bathtub',
    'battery charged',
    'battery charging',
    'battery',
    'bed',
    'bee',
    'beer bottle',
    'beer',
    'bell notification',
    'bell off',
    'bell',
    'belt',
    'bicycle',
    'bikini',
    'binoculars',
    'blood pressure',
    'bluetooth',
    'boarding pass',
    'boat',
    'bomb',
    'bone',
    'book closed',
    'book',
    'bookmark outline',
    'bookmark',
    'boombox',
    'boot',
    'bounce',
    'bowl food',
    'bowl',
    'bowling',
    'bra',
    'brain',
    'branch create',
    'branch fork',
    'branch merge',
    'branch',
    'bread',
    'briefcase',
    'brightness high',
    'broccoli',
    'broom and dustpan',
    'broom',
    'browser stop',
    'bug',
    'bugle',
    'bullseye',
    'bunk bed',
    'burger',
    'burst',
    'bus double decker',
    'bus metro',
    'bus',
    'butterfly',
    'button',
    'cactus',
    'cafe',
    'cake',
    'calculator',
    'calendar day',
    'calendar month',
    'calendar week',
    'calendar',
    'camera off',
    'camera roll portrait',
    'camera roll',
    'camera',
    'camping tent',
    'camping trailer',
    'cancer',
    'candy',
    'capricorn',
    'car',
    'card club',
    'card diamond',
    'card heart',
    'card spade',
    'card',
    'cards',
    'carrot',
    'cash register',
    'cash',
    'cassette',
    'castle japanese',
    'castle',
    'cat',
    'categories',
    'cd',
    'cellular',
    'chair',
    'champagne bottle',
    'champagne',
    'chart alternate',
    'chart area',
    'chart donut',
    'chart line',
    'chart mixed',
    'chart pie',
    'chart',
    'chat user',
    'chat',
    'check',
    'checklist',
    'checkmark line',
    'checkmark square',
    'checkmark',
    'chemistry',
    'cherries',
    'chess bishop',
    'chess king',
    'chess knight',
    'chess pawn',
    'chess queen',
    'chess rook',
    'chevrons vertical',
    'chicken',
    'child',
    'chili pepper',
    'christmas tree',
    'church',
    'cigarette',
    'circle alternate',
    'circle arrows horizontal',
    'circle arrows vertical',
    'circle dashed',
    'circle dot',
    'circle five eighths',
    'circle four eighths',
    'circle one eighth',
    'circle remove',
    'circle seven eighths',
    'circle six eighths',
    'circle three eighths',
    'circle two eighths',
    'circle',
    'city',
    'clarinet',
    'clear',
    'clipping',
    'clock alternate',
    'clock',
    'close',
    'clothes button',
    'clothes iron',
    'cloud no',
    'cloud off',
    'cloud yes',
    'cloud',
    'cloudy',
    'clover four leaf',
    'clover',
    'coaster',
    'coat',
    'cocktail',
    'code scan',
    'code',
    'coffee maker',
    'coffee',
    'color palette',
    'color picker',
    'color swatch',
    'column',
    'comb',
    'command line',
    'comment',
    'compass',
    'compose',
    'compressed document',
    'computer chip',
    'computer',
    'conceal',
    'condense',
    'confetti ball',
    'confetti party popper',
    'conifer tree',
    'connecting flight',
    'construction crane',
    'contrast',
    'conversation',
    'copy',
    'corn',
    'couch',
    'cow',
    'crab',
    'crayon',
    'create',
    'credit card',
    'crop',
    'crutch',
    'cupcake',
    'currency coin',
    'currency',
    'cursor button',
    'cursor click',
    'cursor',
    'customs',
    'cut',
    'dairy',
    'daisy',
    'dance',
    'darks',
    'dashboard',
    'database',
    'defibrillator',
    'delete',
    'delivery truck',
    'dental',
    'departures',
    'dependency',
    'description',
    'dialogue',
    'die1',
    'die2',
    'die3',
    'die4',
    'die5',
    'die6',
    'dining',
    'directional sign left',
    'directional sign right',
    'directional sign',
    'directions',
    'dish soap',
    'dna',
    'do not disturb',
    'document',
    'dog',
    'donkey',
    'download',
    'downward',
    'drafts',
    'dress',
    'drink',
    'duck',
    'duster',
    'ear hearing aid',
    'ear',
    'earthquake',
    'egg',
    'eject',
    'electric guitar',
    'electric plug',
    'elephant',
    'elevator',
    'emoji angry',
    'emoji big sad',
    'emoji disappointed',
    'emoji grinning smiling eyes',
    'emoji grinning',
    'emoji heart eyes',
    'emoji neutral',
    'emoji sad',
    'emoji smiling eyes',
    'emoji sunglasses',
    'emoji surprised',
    'emoji winking',
    'emoji',
    'error',
    'escalator',
    'exclamation mark double',
    'exclamation mark',
    'exit',
    'expand',
    'extension',
    'fabric swatch',
    'facial tissues',
    'factory',
    'fan deck',
    'feather',
    'feed',
    'filtered',
    'fire extinguisher',
    'fire truck',
    'fire',
    'fireworks',
    'first aid kit',
    'first aid',
    'fish',
    'flag checkered',
    'flag pennant',
    'flag swallowtail',
    'flag',
    'flash',
    'flashlight',
    'flatware',
    'fleur de lis',
    'flood',
    'fog',
    'folder',
    'follow',
    'following',
    'font',
    'food and drink',
    'football',
    'forest fire',
    'fork and knife',
    'fork',
    'formula',
    'forward',
    'fragile',
    'friends',
    'frying pan',
    'fuel',
    'game pawn',
    'garlic',
    'gavel',
    'gear',
    'gears',
    'gem',
    'gemini',
    'geography',
    'ghost',
    'gift',
    'git',
    'glasses',
    'globe',
    'golf',
    'government',
    'gradebook',
    'graduate',
    'grapes',
    'grave',
    'grid dense',
    'grid wide six',
    'grid wide',
    'grid',
    'grocery',
    'groups',
    'guitar',
    'gym',
    'hail',
    'hair care',
    'hairdryer',
    'hammer',
    'hanafuda',
    'hand',
    'handbag',
    'hanger',
    'hare',
    'hashtag',
    'headphones',
    'headset',
    'heart box bow',
    'heart outline',
    'heart rate monitor',
    'heart rate',
    'heart',
    'heartbroken',
    'helicopter',
    'helm',
    'help alternate',
    'hexagon alternate',
    'hexagon dashed',
    'hexagon five sixths',
    'hexagon four sixths',
    'hexagon one sixth',
    'hexagon three sixths',
    'hexagon two sixths',
    'hexagon',
    'highball',
    'history',
    'home',
    'hot air balloon',
    'hourglass',
    'hurricane',
    'ice skate',
    'immigration',
    'inbox',
    'infinity',
    'info alternate',
    'inline skate',
    'invitation',
    'iterate',
    'jack o lantern',
    'jar',
    'judicial scales',
    'junk',
    'key antique',
    'key',
    'keyboard alternate',
    'keyboard',
    'keypad',
    'kind',
    'kite',
    'knife kitchen',
    'knife',
    'language',
    'laptop',
    'laundry basket',
    'laundry detergent',
    'laundry dryer',
    'laundry washer',
    'layers',
    'leaf monstera',
    'leaf',
    'lemon',
    'leo',
    'libra',
    'library',
    'light bulb',
    'lights',
    'link',
    'lipstick',
    'list indent',
    'list',
    'litter disposal',
    'location',
    'lock keyhole',
    'lock',
    'log in',
    'log out',
    'long bone',
    'long sleeve shirt',
    'looped square',
    'lost and found',
    'lounge',
    'luggage cart',
    'luggage',
    'lungs',
    'magic wand',
    'magnet',
    'mahjong',
    'mail',
    'makeup brush',
    'mandir',
    'map pin alternate',
    'map pin',
    'map',
    'mathematics',
    'meat',
    'medication',
    'meeting',
    'megaphone',
    'menorah',
    'menstrual pad',
    'merge',
    'metronome',
    'microphone off',
    'microphone',
    'microscope',
    'microwave',
    'midtones',
    'mirror',
    'mobile',
    'monorail',
    'moon',
    'mop and bucket',
    'mop',
    'more',
    'mosque',
    'motorcycle',
    'mountains',
    'mouth',
    'move document',
    'move',
    'movie camera',
    'movie clapboard play',
    'movie clapboard',
    'movie',
    'mushroom',
    'music album',
    'music artist',
    'music',
    'navigation',
    'necktie',
    'network',
    'new alert',
    'new badge',
    'new document',
    'new folder',
    'news',
    'no entry',
    'no',
    'note eighth',
    'note half',
    'note quarter',
    'note sixteenth beamed',
    'note sixteenth',
    'note whole',
    'notification',
    'notion',
    'numero',
    'nut',
    'octagon',
    'official document',
    'onion',
    'orange',
    'orbit',
    'ornament',
    'oven',
    'package',
    'paifang',
    'paint brush wide',
    'paint brush',
    'paint bucket',
    'paint roller',
    'palm tree',
    'pants',
    'paper towels',
    'parking no',
    'parking',
    'partly cloudy day',
    'partly cloudy night',
    'passport',
    'paste',
    'peace',
    'peanut',
    'pear',
    'pen',
    'pencil',
    'pentagon alternate',
    'pentagon dashed',
    'pentagon four fifths',
    'pentagon one fifth',
    'pentagon three fifths',
    'pentagon two fifths',
    'pentagon',
    'people',
    'perfume',
    'person feminine',
    'person masculine',
    'phone call',
    'phone end call',
    'phone speaker',
    'phone',
    'photo landscape',
    'piano',
    'pig',
    'pill',
    'pin',
    'pisces',
    'pitcher',
    'pizza',
    'plate food',
    'playback fast forward',
    'playback next',
    'playback pause',
    'playback play button',
    'playback play',
    'playback previous',
    'playback rewind',
    'playback stop',
    'playlist',
    'plus',
    'poo',
    'postage stamp',
    'postcard',
    'pot',
    'potted plant',
    'poultry',
    'power',
    'pram',
    'pregnancy test',
    'pretzel',
    'preview',
    'print',
    'priority high',
    'priority low',
    'priority mid',
    'private',
    'profile',
    'promoted',
    'public',
    'pull request',
    'pump bottle',
    'pump',
    'push pin',
    'puzzle',
    'question mark',
    'radio',
    'rain',
    'rainbow',
    'receipt',
    'redirect',
    'redo',
    'reference',
    'refresh reverse',
    'refresh',
    'refrigerator',
    'remove',
    'rename',
    'reorder',
    'repeat',
    'reply all',
    'reply',
    'report',
    'ringed planet',
    'robot',
    'rocket',
    'roller skate',
    'row',
    'rubber stamp',
    'ruler',
    'run',
    'safety pin',
    'sagittarius',
    'sailboat',
    'sandwich',
    'save',
    'scarf',
    'school',
    'science',
    'scooter',
    'scorpio',
    'screwdriver',
    'script',
    'scrub brush',
    'search',
    'seed',
    'send to',
    'send',
    'server',
    'service counter',
    'set square',
    'share',
    'sharing',
    'sheep',
    'shell',
    'shield',
    'shirt',
    'shoe',
    'shogi',
    'shop',
    'shopping bag',
    'shopping basket',
    'shopping cart',
    'shorts',
    'shovel and pail',
    'shower',
    'shuffle',
    'sign in',
    'sign out',
    'signature document',
    'sink',
    'skateboard',
    'skip backward',
    'skip forward',
    'skirt',
    'skull profile',
    'skull',
    'sleet',
    'slide',
    'sliders horizontal',
    'sliders vertical',
    'slideshow play',
    'slideshow',
    'smoking no',
    'smoking',
    'snake',
    'snare drum',
    'snippet',
    'snorkel',
    'snowflake',
    'soap',
    'soccer',
    'sock',
    'soda bottle',
    'soft serve',
    'soy',
    'spider',
    'sponge',
    'spoon',
    'spray bottle',
    'square alternate',
    'square dashed',
    'square one fourth',
    'square three fourths',
    'square two fourths',
    'square',
    'squeeze tube',
    'stairs',
    'star half',
    'star of life',
    'star outline',
    'star',
    'stars',
    'steering wheel',
    'stethoscope',
    'sticker',
    'stomach',
    'stopwatch',
    'storm',
    'stovetop',
    'strawberry',
    'stroller',
];



//Mode checker.
let spath;
function modeMode() {
    if (!toggle.checked) {
        spath = '../notion_icons_white/';
    } else {
        spath = '../notion_icons_black/';
    }
}
modeMode();//Loaded once
toggle.addEventListener('change', modeMode);//For listning for more.

// Filter and display suggestions based on input
function showSuggestions() {
    const input = searchInput.value.toLowerCase();
    suggestionsList.innerHTML = '';

    if (!input) {
        suggestionsList.style.display = 'none';
        return;
    }

    const filteredItems = items.filter(item =>
        item.toLowerCase().includes(input)
    );

    if (filteredItems.length === 0) {
        suggestionsList.style.display = 'none';
        return;
    }

    filteredItems.forEach((item, index) => {
        const li = document.createElement('li');
        li.textContent = item;
        li.setAttribute('role', 'option');
        li.setAttribute('data-index', index);

        li.addEventListener('click', () => {
            searchInput.value = item;
            finalQuery = searchInput.value;
            suggestionsList.style.display = 'none';
            let query = 'icon-' + finalQuery.replace(/\s+/g, '-') + '.svg';
            const svgPath = spath + query;

            // ADD THIS LINE - Actually load the SVG inline
            loadSVGInline(svgPath, finalQuery);

            logToPage(svgPath);
        });

        suggestionsList.appendChild(li);
    });

    suggestionsList.style.display = 'block';
}

searchInput.addEventListener('input', showSuggestions);

// Hide suggestions if clicking outside the search box or suggestions
document.addEventListener('click', (event) => {
    if (!event.target.closest('.search-container')) {
        suggestionsList.style.display = 'none';
    }
});


//Icon Holder
function loadSVGInline(svgPath, altText) {
    fetch(svgPath)
        .then(response => response.text())
        .then(svgContent => {
            const container = document.getElementById('iconContainer');
            container.innerHTML = svgContent;

            // Get the SVG element
            const svg = container.querySelector('svg');
            if (svg) {
                // Set size
                svg.setAttribute('width', '48');
                svg.setAttribute('height', '48');
                svg.setAttribute('aria-label', altText);

                // Store the SVG path for later use
                svg.dataset.iconPath = svgPath;

            }
        })
        .catch(error => {
            console.error('Error loading SVG:', error);
        });
}



//Color changer

const colorBoxes = document.querySelectorAll('.color-box');

// Set each box's background color from data-color attribute
colorBoxes.forEach(box => {
    box.style.backgroundColor = box.getAttribute('data-color');
});

colorBoxes.forEach(box => {
    box.addEventListener('click', () => {
        const selectedColor = box.getAttribute('data-color');

        // Remove 'selected' class from all boxes first
        colorBoxes.forEach(b => b.classList.remove('selected'));

        // Add 'selected' class to clicked box
        box.classList.add('selected');

        // ADD THIS LINE - Actually apply the color
        applyColorToIcon(selectedColor);
    });
});


//
function applyColorToIcon(color) {
    const container = document.getElementById('iconContainer');
    const svg = container.querySelector('svg');

    if (svg) {
        // Change fill color of all paths in the SVG
        const paths = svg.querySelectorAll('path, circle, rect, polygon, ellipse');
        paths.forEach(shape => {
            shape.setAttribute('fill', color);
        });

        // Also set fill on the svg element itself
        svg.style.fill = color;

    }
}

//Output handles
    function logToPage(message) {
        console.log(message); // Log to console as usual

        const consoleOutput = document.getElementById('consoleOutput');
        consoleOutput.textContent += message + '\n'; // Append message to the HTML element
    }

});

